import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import { Suspense } from "react";
import LoadingSpinner from "./ui/components/LoadingSpinner";
import { SettingsProvider } from "./context/SettingsContext";
import SideBar from "./ui/image-generation/SideBar";
import ImageGenerationHeader from "./ui/image-generation/ImageGenerationHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body-gradient`}>
        <Providers>
          <SettingsProvider>
            <Suspense
              fallback={
                <div className="flex w-full h-full justify-center items-center">
                  <LoadingSpinner />
                </div>
              }
            >
              <main className="grid grid-cols-main-page-grid h-full">
                <SideBar />
                <div className="flex flex-col flex-1 w-full pl-[17rem]">
                  <ImageGenerationHeader />
                  <div className="flex w-full border-t border-van-gogh-grey-2xd px-8">
                    {children}
                  </div>
                </div>
              </main>
            </Suspense>
          </SettingsProvider>
        </Providers>
      </body>
    </html>
  );
}
