import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import LoadingSpinner from "./ui/components/LoadingSpinner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Suspense
          fallback={
            <div className="flex w-full h-full justify-center items-center">
              <LoadingSpinner />
            </div>
          }
        >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
